name: Pytest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: install poetry
        run: |
          python -m pip install --upgrade poetry
      - name: install dependencies
        run: |
          poetry install
      - name: run tests suite
        run: |
          poetry run pytest -v